# Generated by scripts/generate.py from upstream/. Do not edit.
"""Test messages to the owner's Home conversation."""

import asyncio
from datetime import timedelta
from unittest.mock import patch

import pytest

from homeassistant.components.notify import (
    ATTR_MESSAGE,
    ATTR_TITLE,
    DOMAIN as NOTIFY_DOMAIN,
    SERVICE_SEND_MESSAGE,
)
from homeassistant.const import ATTR_ENTITY_ID, STATE_UNAVAILABLE
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.util import dt as dt_util

from .conftest import MACHINE_ID, FakeChannel

from pytest_homeassistant_custom_component.common import MockConfigEntry, async_fire_time_changed

ENTITY = "notify.home_test_a_airdr_es_home_conversation"


async def _send(hass: HomeAssistant, message: str, title: str | None = None) -> None:
    data = {ATTR_ENTITY_ID: ENTITY, ATTR_MESSAGE: message}
    if title is not None:
        data[ATTR_TITLE] = title
    await hass.services.async_call(
        NOTIFY_DOMAIN, SERVICE_SEND_MESSAGE, data, blocking=True
    )


async def _answered(
    hass: HomeAssistant, channel: FakeChannel, outcome: str, title: str | None = None
) -> None:
    """Send a message; the operator answers ``outcome``."""
    before = len(channel.sent_of("notify"))
    task = hass.async_create_task(_send(hass, "The washer is done", title))
    for _ in range(100):
        await asyncio.sleep(0)
        if len(channel.sent_of("notify")) > before:
            break
    sent = channel.sent_of("notify")[-1]
    assert sent["text"] == "The washer is done"
    assert sent.get("title") == title
    await channel.feed(
        hass,
        channel.frames("notify_result", messageId=sent["messageId"], outcome=outcome),
    )
    await task


async def test_a_message_reaches_the_home_conversation(
    hass: HomeAssistant, init_integration: MockConfigEntry, channel: FakeChannel
) -> None:
    """A delivered message returns; the entity records when it was sent."""
    state = hass.states.get(ENTITY)
    assert state is not None
    await _answered(hass, channel, "delivered", title="Laundry")
    state = hass.states.get(ENTITY)
    assert state is not None and state.state not in ("unknown", STATE_UNAVAILABLE)


@pytest.mark.parametrize(
    ("outcome", "key"),
    [
        ("rate_limited", "notify_rate_limited"),
        ("disabled", "notify_disabled"),
        ("too_long", "notify_too_long"),
        ("rejected", "notify_rejected"),
        ("failed", "notify_failed"),
    ],
)
async def test_a_refused_message_raises_why(
    hass: HomeAssistant,
    init_integration: MockConfigEntry,
    channel: FakeChannel,
    outcome: str,
    key: str,
) -> None:
    """Past the operator's limit, or switched off there, the action fails."""
    with pytest.raises(HomeAssistantError) as raised:
        await _answered(hass, channel, outcome)
    assert raised.value.translation_key == key


async def test_no_message_while_the_channel_is_down(
    hass: HomeAssistant, init_integration: MockConfigEntry, channel: FakeChannel
) -> None:
    """Never queued: a message while disconnected fails at once."""
    channel.open_error = OSError("down")
    channel.queue.put_nowait(None)
    await hass.async_block_till_done()
    async_fire_time_changed(hass, dt_util.utcnow() + timedelta(seconds=11))
    await hass.async_block_till_done()
    assert hass.states.get(ENTITY).state == STATE_UNAVAILABLE
    session = init_integration.runtime_data.session
    assert not session.connected
    entity = hass.data["entity_components"][NOTIFY_DOMAIN].get_entity(ENTITY)
    with pytest.raises(HomeAssistantError) as raised:
        await entity.async_send_message("hello")
    assert raised.value.translation_key == "notify_not_connected"


async def test_an_unanswered_message_times_out(
    hass: HomeAssistant, init_integration: MockConfigEntry, channel: FakeChannel
) -> None:
    """The operator never answers: the action fails, bounded."""
    with (
        patch("custom_components.airdress.notify.NOTIFY_TIMEOUT", 0.01),
        pytest.raises(HomeAssistantError) as raised,
    ):
        await _send(hass, "hello")
    assert raised.value.translation_key == "notify_not_connected"


async def test_the_unique_id(
    hass: HomeAssistant, init_integration: MockConfigEntry
) -> None:
    """One conversation per linked airdress."""
    entity = hass.data["entity_components"][NOTIFY_DOMAIN].get_entity(ENTITY)
    assert entity is not None and entity.unique_id == f"{MACHINE_ID}-conversation"


async def test_a_planned_redial_keeps_the_entities_available(
    hass: HomeAssistant, init_integration: MockConfigEntry, channel: FakeChannel
) -> None:
    """The operator's hourly re-dial is over before anything goes unavailable.

    It used to flip every entity unavailable for a second at the same minute
    of every hour (the owner's Green, 2026-09-29, 00:39 through 06:39).
    """
    seen: list[str] = []
    hass.bus.async_listen(
        "state_changed",
        lambda event: (
            seen.append(event.data["new_state"].state)
            if event.data["entity_id"] == ENTITY and event.data["new_state"]
            else None
        ),
    )
    channel.close_code = 4001
    with patch("airdress_home.session.random.uniform", return_value=0.0):
        channel.queue.put_nowait(None)
        for _ in range(50):
            await asyncio.sleep(0.01)
            if channel.opened == 2:
                break
    assert not init_integration.runtime_data.session.connected
    await channel.connect(hass)
    assert init_integration.runtime_data.session.connected
    async_fire_time_changed(hass, dt_util.utcnow() + timedelta(seconds=11))
    await hass.async_block_till_done()
    assert STATE_UNAVAILABLE not in seen
    assert hass.states.get(ENTITY).state != STATE_UNAVAILABLE


async def test_an_unload_inside_the_grace_leaves_nothing_scheduled(
    hass: HomeAssistant, init_integration: MockConfigEntry, channel: FakeChannel
) -> None:
    """Unloading while the channel is down cancels the pending unavailability."""
    channel.open_error = OSError("down")
    channel.queue.put_nowait(None)
    await hass.async_block_till_done()
    hub = init_integration.runtime_data.hub
    assert hub.available
    await hass.config_entries.async_unload(init_integration.entry_id)
    await hass.async_block_till_done()
    async_fire_time_changed(hass, dt_util.utcnow() + timedelta(seconds=11))
    await hass.async_block_till_done()
    assert hub.available, "nothing ran after the unload"
