# Generated by scripts/generate.py from upstream/. Do not edit.
"""Test the Airdress config flow."""

import asyncio
from collections.abc import Generator
from unittest.mock import AsyncMock, patch

import aiohttp
from airdress_home import (
    EnrollmentDenied,
    EnrollmentError,
    EnrollmentExpired,
    NotAuthorized,
    OperatorProofError,
)
import pytest

from custom_components.airdress.const import (
    CONF_KID,
    CONF_MACHINE_ID,
    CONF_MACHINE_KEY,
    CONF_OBSERVE,
    CONF_OPERATE,
    CONF_OPERATOR,
    CONF_OPERATOR_KEY,
    CONF_PREAUTH_KEY,
    CONF_RECORD_LOCATION,
    CONF_SENSITIVE,
    DOMAIN,
    REAUTH_REFUSAL,
)
from homeassistant.config_entries import SOURCE_USER
from homeassistant.const import ATTR_DEVICE_CLASS, CONF_ADDRESS
from homeassistant.core import HomeAssistant
from homeassistant.data_entry_flow import FlowResultType
from homeassistant.helpers import entity_registry as er

from .conftest import ENROLLMENT, LINK, MACHINE_KEY, ORIGIN, started

from pytest_homeassistant_custom_component.common import MockConfigEntry

EXPECTED_DATA = {
    CONF_OPERATOR: ORIGIN,
    CONF_MACHINE_ID: ENROLLMENT.machine_id,
    CONF_KID: ENROLLMENT.kid,
    CONF_OPERATOR_KEY: ENROLLMENT.operator_key,
    CONF_MACHINE_KEY: MACHINE_KEY.seed_b64(),
}


async def _menu(hass: HomeAssistant, choice: str) -> str:
    result = await hass.config_entries.flow.async_init(
        DOMAIN, context={"source": SOURCE_USER}
    )
    assert result["type"] is FlowResultType.MENU
    assert result["menu_options"] == ["link", "address", "preauth"]
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"next_step_id": choice}
    )
    return result["flow_id"]


async def _approve(hass: HomeAssistant, flow_id: str, approval: asyncio.Event) -> dict:
    approval.set()
    await hass.async_block_till_done()
    return await hass.config_entries.flow.async_configure(flow_id)


@pytest.mark.usefixtures("mock_setup_entry")
async def test_sign_in_with_airdress(
    hass: HomeAssistant,
    mock_hub: dict[str, AsyncMock],
    mock_enroll: dict[str, AsyncMock],
    bound: asyncio.Event,
    approval: asyncio.Event,
) -> None:
    """The hub introduces the operator; the owner approves there."""
    result = await hass.config_entries.flow.async_init(
        DOMAIN, context={"source": SOURCE_USER}
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"next_step_id": "link"}
    )
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    assert result["progress_action"] == "link"
    assert result["description_placeholders"] == {
        "url": LINK.verification_uri_complete,
        "code": LINK.user_code,
    }
    assert mock_hub["start"].call_args.kwargs == {"client_name": "Home Assistant"}

    bound.set()
    await hass.async_block_till_done()
    result = await hass.config_entries.flow.async_configure(result["flow_id"])
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    assert result["step_id"] == "approve"
    assert result["description_placeholders"]["user_code"] == "ABCD-EFGH"
    assert (
        result["description_placeholders"]["confirmation_code"]
        == "AAAA-BBBB-CCCC-DDDD-EEEE"
    )
    args, kwargs = mock_enroll["start"].call_args
    assert args[1] == ORIGIN
    assert kwargs == {"preauth_key": None, "require_proof": True}
    assert mock_hub["enrolled"].call_args.args[2] == "ABCD-EFGH"

    result = await _approve(hass, result["flow_id"], approval)
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert result["title"] == "home-test.a.airdr.es"
    assert result["data"] == EXPECTED_DATA
    assert result["options"] == {CONF_OPERATE: [], CONF_OBSERVE: [], CONF_SENSITIVE: []}
    assert result["result"].unique_id == ORIGIN


@pytest.mark.usefixtures("mock_setup_entry", "mock_enroll")
async def test_sign_in_when_the_hub_is_not_told(
    hass: HomeAssistant,
    mock_hub: dict[str, AsyncMock],
    bound: asyncio.Event,
    approval: asyncio.Event,
) -> None:
    """The approve link still works when the hub is not told of the enrollment."""
    mock_hub["enrolled"].side_effect = EnrollmentError("not_bound")
    flow_id = await _menu(hass, "link")
    bound.set()
    await hass.async_block_till_done()
    result = await hass.config_entries.flow.async_configure(flow_id)
    assert result["step_id"] == "approve"
    result = await _approve(hass, flow_id, approval)
    assert result["type"] is FlowResultType.CREATE_ENTRY


@pytest.mark.parametrize(
    "error", [EnrollmentError("temporarily_unavailable"), aiohttp.ClientError()]
)
async def test_sign_in_hub_unreachable(
    hass: HomeAssistant, mock_hub: dict[str, AsyncMock], error: Exception
) -> None:
    """A hub that cannot start a link aborts, to be retried."""
    mock_hub["start"].side_effect = error
    result = await hass.config_entries.flow.async_init(
        DOMAIN, context={"source": SOURCE_USER}
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"next_step_id": "link"}
    )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "cannot_connect_hub"


@pytest.mark.parametrize(
    ("error", "reason"),
    [
        (EnrollmentDenied("denied"), "link_denied"),
        (EnrollmentExpired("expired"), "link_expired"),
        (EnrollmentError("bad_origin"), "cannot_connect_hub"),
        (TimeoutError(), "cannot_connect_hub"),
    ],
)
async def test_sign_in_not_bound(
    hass: HomeAssistant,
    mock_hub: dict[str, AsyncMock],
    error: Exception,
    reason: str,
) -> None:
    """The owner declined at the hub, or the code expired."""
    mock_hub["poll"].side_effect = error
    result = await hass.config_entries.flow.async_init(
        DOMAIN, context={"source": SOURCE_USER}
    )
    result = await hass.config_entries.flow.async_configure(
        result["flow_id"], {"next_step_id": "link"}
    )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == reason


@pytest.mark.usefixtures("mock_hub")
async def test_sign_in_to_an_airdress_already_linked(
    hass: HomeAssistant,
    mock_config_entry: MockConfigEntry,
    mock_enroll: dict[str, AsyncMock],
    bound: asyncio.Event,
) -> None:
    """A second link to the same airdress aborts before enrolling."""
    mock_config_entry.add_to_hass(hass)
    flow_id = await _menu(hass, "link")
    bound.set()
    await hass.async_block_till_done()
    result = await hass.config_entries.flow.async_configure(flow_id)
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "already_configured"
    mock_enroll["start"].assert_not_called()


@pytest.mark.usefixtures("mock_hub")
async def test_sign_in_operator_proof_fails(
    hass: HomeAssistant, mock_enroll: dict[str, AsyncMock], bound: asyncio.Event
) -> None:
    """An operator whose answer does not verify is not trusted."""
    mock_enroll["start"].side_effect = OperatorProofError("bad")
    flow_id = await _menu(hass, "link")
    bound.set()
    await hass.async_block_till_done()
    result = await hass.config_entries.flow.async_configure(flow_id)
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "operator_proof"


@pytest.mark.usefixtures("mock_setup_entry")
async def test_link_by_address(
    hass: HomeAssistant, mock_enroll: dict[str, AsyncMock], approval: asyncio.Event
) -> None:
    """A typed address, normalized to its origin, then approval."""
    mock_enroll["start"].return_value = started(complete=None)
    flow_id = await _menu(hass, "address")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: " Home-Test.a.airdr.es/ "}
    )
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    assert result["description_placeholders"]["url"] == f"{ORIGIN}/machines/approve"
    assert mock_enroll["start"].call_args.args[1] == ORIGIN
    result = await _approve(hass, flow_id, approval)
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert result["data"] == EXPECTED_DATA


@pytest.mark.usefixtures("mock_enroll")
async def test_approve_url_when_the_operator_names_none(
    hass: HomeAssistant, mock_enroll: dict[str, AsyncMock]
) -> None:
    """An operator that names no approval page gets its standard one."""
    answer = started(complete=None)
    answer.verification_uri = None
    mock_enroll["start"].return_value = answer
    flow_id = await _menu(hass, "address")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN}
    )
    assert result["description_placeholders"]["url"] == f"{ORIGIN}/machines/approve"


@pytest.mark.parametrize(
    ("error", "reason"),
    [
        (EnrollmentError("not_enabled"), "not_enabled"),
        (EnrollmentError("slow_down"), "busy"),
        (EnrollmentError("server_error"), "enroll_refused"),
        (OperatorProofError("no proof"), "operator_proof"),
        (aiohttp.ClientError(), "cannot_connect"),
        (TimeoutError(), "cannot_connect"),
    ],
)
@pytest.mark.usefixtures("mock_setup_entry")
async def test_link_by_address_errors_can_be_retried(
    hass: HomeAssistant,
    mock_enroll: dict[str, AsyncMock],
    approval: asyncio.Event,
    error: Exception,
    reason: str,
) -> None:
    """Each refusal is shown on the form, and the form can be sent again."""
    mock_enroll["start"].side_effect = error
    flow_id = await _menu(hass, "address")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN}
    )
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {"base": reason}
    mock_enroll["start"].side_effect = None
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN}
    )
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    result = await _approve(hass, flow_id, approval)
    assert result["type"] is FlowResultType.CREATE_ENTRY


@pytest.mark.parametrize(
    "address", ["http://home-test.a.airdr.es", "https://x.example/path", "https://"]
)
async def test_link_by_address_invalid(
    hass: HomeAssistant, mock_enroll: dict[str, AsyncMock], address: str
) -> None:
    """Only a bare https origin is an airdress's address."""
    flow_id = await _menu(hass, "address")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: address}
    )
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {CONF_ADDRESS: "invalid_address"}
    mock_enroll["start"].assert_not_called()


@pytest.mark.usefixtures("mock_enroll")
async def test_link_by_address_already_linked(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry
) -> None:
    """One entry per airdress."""
    mock_config_entry.add_to_hass(hass)
    flow_id = await _menu(hass, "address")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN}
    )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "already_configured"


@pytest.mark.usefixtures("mock_setup_entry")
async def test_link_with_a_preauth_key(
    hass: HomeAssistant, mock_enroll: dict[str, AsyncMock], approval: asyncio.Event
) -> None:
    """A refused key is shown on the form; a good one links."""
    mock_enroll["start"].side_effect = EnrollmentError("access_denied")
    flow_id = await _menu(hass, "preauth")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN, CONF_PREAUTH_KEY: "wrong"}
    )
    assert result["errors"] == {"base": "invalid_preauth_key"}
    mock_enroll["start"].side_effect = None
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN, CONF_PREAUTH_KEY: "adk_good"}
    )
    assert mock_enroll["start"].call_args.kwargs["preauth_key"] == "adk_good"
    result = await _approve(hass, flow_id, approval)
    assert result["type"] is FlowResultType.CREATE_ENTRY


@pytest.mark.parametrize(
    ("error", "reason"),
    [
        (EnrollmentDenied("access_denied"), "denied"),
        (EnrollmentExpired("expired_token"), "expired"),
        (EnrollmentError("invalid_grant"), "enroll_refused"),
        (aiohttp.ClientError(), "enroll_refused"),
    ],
)
async def test_approval_not_given(
    hass: HomeAssistant,
    mock_enroll: dict[str, AsyncMock],
    error: Exception,
    reason: str,
) -> None:
    """Denied, expired or failed approvals abort with their reason."""
    mock_enroll["poll"].side_effect = error
    flow_id = await _menu(hass, "address")
    result = await hass.config_entries.flow.async_configure(
        flow_id, {CONF_ADDRESS: ORIGIN}
    )
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == reason


@pytest.mark.usefixtures("mock_enroll", "mock_hub")
async def test_abandoned_flows_stop_waiting(hass: HomeAssistant) -> None:
    """Closing the dialog cancels the waits on the hub and on the operator."""
    flow_id = await _menu(hass, "link")
    flow = hass.config_entries.flow._progress[flow_id]
    link_task = flow._link_task
    hass.config_entries.flow.async_abort(flow_id)
    await hass.async_block_till_done()
    assert link_task.cancelled()

    flow_id = await _menu(hass, "address")
    await hass.config_entries.flow.async_configure(flow_id, {CONF_ADDRESS: ORIGIN})
    flow = hass.config_entries.flow._progress[flow_id]
    approve_task = flow._approve_task
    hass.config_entries.flow.async_abort(flow_id)
    await hass.async_block_till_done()
    assert approve_task.cancelled()


async def test_options_levels_without_sensitive_entities(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry
) -> None:
    """Choosing entities with nothing sensitive among them is one step."""
    mock_config_entry.add_to_hass(hass)
    hass.states.async_set("button.office_pc", "unknown")
    result = await hass.config_entries.options.async_init(mock_config_entry.entry_id)
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "init"
    result = await hass.config_entries.options.async_configure(
        result["flow_id"],
        {CONF_OPERATE: ["button.office_pc"], CONF_OBSERVE: ["sensor.washer"]},
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert mock_config_entry.options == {
        CONF_OPERATE: ["button.office_pc"],
        CONF_OBSERVE: ["sensor.washer"],
        CONF_SENSITIVE: [],
        CONF_RECORD_LOCATION: False,
    }


async def test_options_sensitive_entities_need_their_own_opt_in(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry
) -> None:
    """Locks and entry-point covers are offered for opt-in, none by default."""
    mock_config_entry.add_to_hass(hass)
    hass.config_entries.async_update_entry(
        mock_config_entry,
        options={
            **mock_config_entry.options,
            CONF_SENSITIVE: ["lock.front", "lock.old"],
        },
    )
    hass.states.async_set("lock.front", "locked")
    hass.states.async_set("cover.garage", "closed", {ATTR_DEVICE_CLASS: "garage"})
    hass.states.async_set("cover.blind", "open", {ATTR_DEVICE_CLASS: "blind"})
    result = await hass.config_entries.options.async_init(mock_config_entry.entry_id)
    result = await hass.config_entries.options.async_configure(
        result["flow_id"],
        {CONF_OPERATE: ["lock.front", "cover.garage", "cover.blind"]},
    )
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "sensitive"
    assert result["description_placeholders"] == {"count": "2"}
    schema = result["data_schema"].schema
    (key,) = schema
    assert key.description == {"suggested_value": ["lock.front"]}
    assert schema[key].config["include_entities"] == ["lock.front", "cover.garage"]
    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {CONF_SENSITIVE: ["cover.garage"]}
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert mock_config_entry.options == {
        CONF_OPERATE: ["lock.front", "cover.garage", "cover.blind"],
        CONF_OBSERVE: [],
        CONF_SENSITIVE: ["cover.garage"],
        CONF_RECORD_LOCATION: False,
    }


def _with_tracker(hass: HomeAssistant, entry: MockConfigEntry) -> str:
    entry.add_to_hass(hass)
    reg = er.async_get(hass).async_get_or_create(
        "device_tracker",
        "airdress",
        f"{ENROLLMENT.machine_id}-tracker-jefe",
        config_entry=entry,
        suggested_object_id="home_test_jefe",
    )
    return reg.entity_id


async def test_options_location_defaults_to_not_recording(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry
) -> None:
    """With a tracker, the last step asks, and "no" is the default."""
    tracker = _with_tracker(hass, mock_config_entry)
    result = await hass.config_entries.options.async_init(mock_config_entry.entry_id)
    result = await hass.config_entries.options.async_configure(result["flow_id"], {})
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "location"
    assert result["description_placeholders"] == {"trackers": tracker}
    (key,) = result["data_schema"].schema
    assert key.description == {"suggested_value": False}
    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {CONF_RECORD_LOCATION: False}
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert mock_config_entry.options[CONF_RECORD_LOCATION] is False


async def test_options_recording_needs_a_confirmation(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry
) -> None:
    """Choosing to record shows what it means; back returns, confirming records."""
    _with_tracker(hass, mock_config_entry)
    result = await hass.config_entries.options.async_init(mock_config_entry.entry_id)
    result = await hass.config_entries.options.async_configure(result["flow_id"], {})
    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {CONF_RECORD_LOCATION: True}
    )
    assert result["type"] is FlowResultType.MENU
    assert result["step_id"] == "location_confirm"
    assert result["menu_options"] == ["location_record", "location"]
    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {"next_step_id": "location"}
    )
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "location"
    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {CONF_RECORD_LOCATION: True}
    )
    result = await hass.config_entries.options.async_configure(
        result["flow_id"], {"next_step_id": "location_record"}
    )
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert mock_config_entry.options[CONF_RECORD_LOCATION] is True


async def test_options_without_a_tracker_keep_the_recording_choice(
    hass: HomeAssistant, mock_config_entry: MockConfigEntry
) -> None:
    """No tracker, no question; an earlier choice is kept."""
    mock_config_entry.add_to_hass(hass)
    hass.config_entries.async_update_entry(
        mock_config_entry,
        options={**mock_config_entry.options, CONF_RECORD_LOCATION: True},
    )
    result = await hass.config_entries.options.async_init(mock_config_entry.entry_id)
    result = await hass.config_entries.options.async_configure(result["flow_id"], {})
    assert result["type"] is FlowResultType.CREATE_ENTRY
    assert mock_config_entry.options[CONF_RECORD_LOCATION] is True


@pytest.fixture
def mock_renew() -> Generator[AsyncMock]:
    """The operator's answer to a machine asking to be approved again."""
    with patch(
        "custom_components.airdress.config_flow.start_reauth",
        return_value=started(),
    ) as renew:
        yield renew


@pytest.mark.usefixtures("mock_setup_entry")
async def test_reauth_renews_a_lapsed_machine(
    hass: HomeAssistant,
    mock_config_entry: MockConfigEntry,
    mock_enroll: dict[str, AsyncMock],
    mock_renew: AsyncMock,
    approval: asyncio.Event,
) -> None:
    """A lapsed approval is renewed for the same machine and key."""
    mock_config_entry.add_to_hass(hass)
    before = dict(mock_config_entry.data)
    result = await mock_config_entry.start_reauth_flow(hass)
    assert result["type"] is FlowResultType.FORM
    assert result["step_id"] == "reauth_confirm"
    assert result["description_placeholders"]["operator"] == "home-test.a.airdr.es"

    result = await hass.config_entries.flow.async_configure(result["flow_id"], {})
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    assert result["step_id"] == "approve"
    client = mock_renew.call_args.args[0]
    assert client.enrollment.machine_id == before[CONF_MACHINE_ID]
    assert client.key.seed_b64() == before[CONF_MACHINE_KEY]
    mock_enroll["start"].assert_not_called()

    result = await _approve(hass, result["flow_id"], approval)
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "reauth_successful"
    assert dict(mock_config_entry.data) == before
    assert mock_enroll["poll"].call_args.args[2].seed_b64() == before[CONF_MACHINE_KEY]


@pytest.mark.usefixtures("mock_setup_entry")
async def test_reauth_enrolls_a_new_machine_after_a_revoke(
    hass: HomeAssistant,
    mock_config_entry: MockConfigEntry,
    mock_enroll: dict[str, AsyncMock],
    mock_renew: AsyncMock,
    approval: asyncio.Event,
) -> None:
    """A revoked machine cannot be renewed: a new one is enrolled; sharing is kept."""
    mock_config_entry.add_to_hass(hass)
    hass.config_entries.async_update_entry(
        mock_config_entry,
        data={**mock_config_entry.data, CONF_MACHINE_ID: "the-revoked-machine"},
        options={**mock_config_entry.options, CONF_OPERATE: ["button.office_pc"]},
    )
    mock_renew.side_effect = NotAuthorized("unauthorized")
    result = await mock_config_entry.start_reauth_flow(hass)
    result = await hass.config_entries.flow.async_configure(result["flow_id"], {})
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    assert mock_enroll["start"].call_args.args[1] == ORIGIN

    result = await _approve(hass, result["flow_id"], approval)
    assert result["type"] is FlowResultType.ABORT
    assert result["reason"] == "reauth_successful"
    assert dict(mock_config_entry.data) == EXPECTED_DATA
    assert mock_config_entry.options[CONF_OPERATE] == ["button.office_pc"]


@pytest.mark.usefixtures("mock_setup_entry")
@pytest.mark.parametrize(("refusal", "renewed"), [("revoked", False), ("lapsed", True)])
async def test_reauth_follows_the_refusal(
    hass: HomeAssistant,
    mock_config_entry: MockConfigEntry,
    mock_enroll: dict[str, AsyncMock],
    mock_renew: AsyncMock,
    refusal: str,
    renewed: bool,
) -> None:
    """Revoked goes straight to a new enrollment; lapsed asks for a renewal."""
    mock_config_entry.add_to_hass(hass)
    result = await mock_config_entry.start_reauth_flow(
        hass, data={**mock_config_entry.data, REAUTH_REFUSAL: refusal}
    )
    result = await hass.config_entries.flow.async_configure(result["flow_id"], {})
    assert result["type"] is FlowResultType.SHOW_PROGRESS
    assert mock_renew.called is renewed
    assert mock_enroll["start"].called is not renewed


@pytest.mark.parametrize(
    ("renew_error", "enroll_error", "reason"),
    [
        (aiohttp.ClientError, None, "cannot_connect"),
        (OperatorProofError("x"), None, "operator_proof"),
        (EnrollmentError("slow_down"), None, "busy"),
        (NotAuthorized("unauthorized"), aiohttp.ClientError, "cannot_connect"),
    ],
)
async def test_reauth_shows_why_the_operator_refused(
    hass: HomeAssistant,
    mock_config_entry: MockConfigEntry,
    mock_enroll: dict[str, AsyncMock],
    mock_renew: AsyncMock,
    renew_error: Exception | type[Exception],
    enroll_error: type[Exception] | None,
    reason: str,
) -> None:
    """A refused renewal or enrollment keeps the form, with the reason."""
    mock_config_entry.add_to_hass(hass)
    mock_renew.side_effect = renew_error
    if enroll_error is not None:
        mock_enroll["start"].side_effect = enroll_error
    result = await mock_config_entry.start_reauth_flow(hass)
    result = await hass.config_entries.flow.async_configure(result["flow_id"], {})
    assert result["type"] is FlowResultType.FORM
    assert result["errors"] == {"base": reason}
