# Generated by scripts/generate.py from upstream/. Do not edit.
"""Test the logbook descriptions of what Airdress runs."""

from custom_components.airdress.const import DOMAIN, EVENT_OPERATE
from homeassistant.core import HomeAssistant
from homeassistant.setup import async_setup_component

from tests.logbook_common import MockRow, mock_humanify


async def test_the_logbook_names_the_function(hass: HomeAssistant) -> None:
    """Each action names the function that asked for it."""
    hass.config.components.add("recorder")
    assert await async_setup_component(hass, "logbook", {})
    assert await async_setup_component(hass, DOMAIN, {})
    await hass.async_block_till_done()

    first, second = mock_humanify(
        hass,
        [
            MockRow(
                EVENT_OPERATE,
                {
                    "function": "wake-on-arrival",
                    "action": "button.press",
                    "entity_id": ["button.office_pc"],
                },
            ),
            MockRow(EVENT_OPERATE, {"action": "script.turn_on", "entity_id": []}),
        ],
    )
    assert first["name"] == "Airdress"
    assert first["message"] == "wake-on-arrival ran button.press"
    assert first["entity_id"] == "button.office_pc"
    assert second["message"] == "a function ran script.turn_on"
    assert "entity_id" not in second or second["entity_id"] is None
