# Generated by scripts/generate.py from upstream/. Do not edit.
"""Events the operator's functions emit to this installation.

The operator's ``Home`` declares its events (a name and the types each can
carry); each becomes an event entity here. A function's ``emit`` triggers one.
"""

from typing import Any

from airdress_home import EventDeclaration, Features

from homeassistant.components.event import EventEntity
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.dispatcher import async_dispatcher_connect
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import AirdressConfigEntry
from .const import CONF_MACHINE_ID, DOMAIN, LOGGER, signal_emit, signal_features
from .entity import AirdressEntity

PARALLEL_UPDATES = 0

ATTR_FUNCTION = "function"


def _unique_id(entry: AirdressConfigEntry, name: str) -> str:
    return f"{entry.data[CONF_MACHINE_ID]}-event-{name}"


class AirdressEvent(AirdressEntity, EventEntity):
    """One event the operator declared."""

    def __init__(self, entry: AirdressConfigEntry, name: str, types: list[str]) -> None:
        """Initialize the event entity."""
        super().__init__(entry)
        self._attr_name = name
        self._attr_unique_id = _unique_id(entry, name)
        self._attr_event_types = types

    @callback
    def async_redeclare(self, types: list[str]) -> None:
        """The operator changed the event's types."""
        if types != self._attr_event_types:
            self._attr_event_types = types
            self.async_write_ha_state()

    @callback
    def async_emitted(
        self, event_type: str, data: dict[str, Any] | None, function: str
    ) -> None:
        """A function emitted this event."""
        if event_type not in self.event_types:
            LOGGER.debug("Dropped an emit of an undeclared type on %s", self.entity_id)
            return
        attributes = dict(data or {})
        attributes[ATTR_FUNCTION] = function
        self._trigger_event(event_type, attributes)
        self.async_write_ha_state()


async def async_setup_entry(
    hass: HomeAssistant,
    entry: AirdressConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    """Set up the operator's declared events."""
    registry = er.async_get(hass)
    known: dict[str, AirdressEvent] = {}
    prefix = f"{entry.data[CONF_MACHINE_ID]}-event-"

    # What the operator declared last time, so the entities exist (unavailable)
    # before the channel is up.
    restored: list[AirdressEvent] = []
    for reg in er.async_entries_for_config_entry(registry, entry.entry_id):
        if reg.domain != Platform.EVENT or not reg.unique_id.startswith(prefix):
            continue
        types = (reg.capabilities or {}).get("event_types")
        if isinstance(types, list) and types:
            name = reg.unique_id.removeprefix(prefix)
            known[name] = AirdressEvent(entry, name, [str(t) for t in types])
            restored.append(known[name])
    async_add_entities(restored)

    @callback
    def _async_declared(features: Features) -> None:
        declared: dict[str, EventDeclaration] = {e.name: e for e in features.events}
        new: list[AirdressEvent] = []
        for name, declaration in declared.items():
            types = list(declaration.types)
            if (entity := known.get(name)) is None:
                known[name] = AirdressEvent(entry, name, types)
                new.append(known[name])
            else:
                entity.async_redeclare(types)
        if new:
            async_add_entities(new)
        for name in [n for n in known if n not in declared]:
            entity = known.pop(name)
            if (
                entity_id := registry.async_get_entity_id(
                    Platform.EVENT, DOMAIN, _unique_id(entry, name)
                )
            ) is not None:
                registry.async_remove(entity_id)

    @callback
    def _async_emitted(
        event: str, event_type: str, data: dict[str, Any] | None, function: str
    ) -> None:
        if (entity := known.get(event)) is None or entity.hass is None:
            LOGGER.debug("Dropped an emit of an undeclared event")
            return
        entity.async_emitted(event_type, data, function)

    entry.async_on_unload(
        async_dispatcher_connect(hass, signal_features(entry.entry_id), _async_declared)
    )
    entry.async_on_unload(
        async_dispatcher_connect(hass, signal_emit(entry.entry_id), _async_emitted)
    )
