#!/usr/bin/env python3
"""Generate custom_components/airdress and tests/ from upstream/ and overlay/.

    scripts/generate.py            # write the generated trees
    scripts/generate.py --check    # fail if they differ from what is committed

Nothing under custom_components/ or tests/airdress/ is edited by hand. Every
difference from the core integration is made here, in one place, and is one
of these:

- the manifest gains `version`, and a `documentation` and `issue_tracker`
  pointing at this repository; it pins the library from overlay/mirror.json;
  and it drops `quality_scale`, which only core integrations carry;
- `strings.json` and `quality_scale.yaml` are left out: a custom integration
  is translated from translations/*.json, and has no quality scale;
- translations/de.json and the brand images come from overlay/;
- in the tests, `homeassistant.components.airdress` becomes
  `custom_components.airdress`, and core's test helpers become the
  custom-component test harness's (`tests.common`) or the copy of core's
  logbook helper (`tests.components.logbook.common`); and because those
  rewrites change line lengths and import sections, the generated tests are
  then sorted and formatted with ruff under tests/ruff.toml, so that they
  pass the same checks core's tests pass.

One line outside those trees is generated too: the library requirement in
requirements_test.txt, so that the tests run against the library the manifest
pins and not an older one (a stale pin there once failed 74 tests while the
manifest named the right release).

CI runs `--check`, so a hand edit, or an upstream/ refresh committed without
regenerating, fails the build.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "upstream"
OVERLAY = ROOT / "overlay"
REPO_URL = "https://github.com/airdress-co/airdress-home-assistant"

# Generated paths, relative to the repository root. --check compares exactly
# these; everything else in the repository is written by hand.
OUT_INTEGRATION = Path("custom_components/airdress")
OUT_TESTS = Path("tests/airdress")
OUT_LOGBOOK_HELPER = Path("tests/logbook_common.py")
TEST_REQUIREMENTS = Path("requirements_test.txt")
LIBRARY_LINE = re.compile(r"^airdress-home\b.*$", re.MULTILINE)

# The ruff that formats the generated tests. It must be the version the prek
# hooks run (.pre-commit-config.yaml), or --check and the hooks disagree.
# RUFF overrides the command, e.g. RUFF=.venv/bin/ruff.
RUFF_VERSION = "0.16.8"

LEFT_OUT = {"strings.json", "quality_scale.yaml"}
HEADER = "# Generated by scripts/generate.py from upstream/. Do not edit.\n"

TEST_REWRITES = (
    (
        re.compile(r"\bhomeassistant\.components\.airdress\b"),
        "custom_components.airdress",
    ),
    (
        re.compile(r"^from tests\.common import", re.MULTILINE),
        "from pytest_homeassistant_custom_component.common import",
    ),
    (
        re.compile(r"^from tests\.components\.logbook\.common import", re.MULTILINE),
        "from tests.logbook_common import",
    ),
)


def ruff() -> list[str]:
    """The command that runs the pinned ruff."""
    if command := os.environ.get("RUFF"):
        return [command]
    return ["uvx", "--quiet", f"ruff@{RUFF_VERSION}"]


def tidy_tests(tests: Path) -> None:
    """Sort imports and format the rewritten tests as core's tests are."""
    config = str(ROOT / "tests/ruff.toml")
    for args in (
        ["check", "--fix", "--select", "I001", "--quiet", "--exit-zero"],
        ["format", "--quiet"],
    ):
        subprocess.run([*ruff(), *args, "--config", config, str(tests)], check=True)


def manifest(source: dict[str, object], mirror: dict[str, str]) -> str:
    """The mirror's manifest.json, from core's and overlay/mirror.json."""
    out = {key: value for key, value in source.items() if key != "quality_scale"}
    out["version"] = mirror["version"]
    out["documentation"] = f"{REPO_URL}#readme"
    out["issue_tracker"] = f"{REPO_URL}/issues"
    out["requirements"] = [mirror["library"]]
    # hassfest's order: domain, name, then the rest alphabetically.
    ordered = {"domain": out.pop("domain"), "name": out.pop("name")}
    ordered.update(sorted(out.items()))
    return json.dumps(ordered, indent=2) + "\n"


def test_requirements(text: str, mirror: dict[str, str]) -> str:
    """Pin the tests to the library the manifest pins."""
    if len(LIBRARY_LINE.findall(text)) != 1:
        sys.exit(f"{TEST_REQUIREMENTS} must name airdress-home on exactly one line")
    return LIBRARY_LINE.sub(mirror["library"], text)


def with_header(text: str) -> str:
    """Mark a file as generated."""
    return HEADER + text


def generate(dest: Path) -> None:
    """Write every generated file under dest."""
    mirror = json.loads((OVERLAY / "mirror.json").read_text())
    src = UPSTREAM / "homeassistant/components/airdress"
    if not (src / "manifest.json").exists():
        sys.exit("upstream/ holds no integration: run scripts/export_upstream.py first")

    integration = dest / OUT_INTEGRATION
    integration.mkdir(parents=True)
    for path in sorted(src.iterdir()):
        if path.name in LEFT_OUT or path.is_dir():
            continue
        if path.name == "manifest.json":
            (integration / path.name).write_text(
                manifest(json.loads(path.read_text()), mirror)
            )
        elif path.suffix == ".py":
            (integration / path.name).write_text(with_header(path.read_text()))
        else:
            shutil.copy2(path, integration / path.name)

    translations = integration / "translations"
    translations.mkdir()
    shutil.copy2(src / "translations/en.json", translations / "en.json")
    for path in sorted((OVERLAY / "translations").glob("*.json")):
        shutil.copy2(path, translations / path.name)

    brand = integration / "brand"
    brand.mkdir()
    for path in sorted((OVERLAY / "brand").glob("*.png")):
        shutil.copy2(path, brand / path.name)

    tests = dest / OUT_TESTS
    tests.mkdir(parents=True)
    for path in sorted((UPSTREAM / "tests/components/airdress").glob("*.py")):
        text = path.read_text()
        for pattern, replacement in TEST_REWRITES:
            text = pattern.sub(replacement, text)
        (tests / path.name).write_text(with_header(text))
    tidy_tests(tests)

    helper = UPSTREAM / "tests/components/logbook/common.py"
    (dest / OUT_LOGBOOK_HELPER).write_text(with_header(helper.read_text()))

    (dest / TEST_REQUIREMENTS).write_text(
        test_requirements((ROOT / TEST_REQUIREMENTS).read_text(), mirror)
    )


def tree_files(base: Path) -> dict[str, bytes]:
    """The generated files under base, by relative path."""
    files: dict[str, bytes] = {}
    for rel in (OUT_INTEGRATION, OUT_TESTS, OUT_LOGBOOK_HELPER, TEST_REQUIREMENTS):
        root = base / rel
        if root.is_file():
            files[str(rel)] = root.read_bytes()
        elif root.is_dir():
            for path in sorted(root.rglob("*")):
                if path.is_file() and "__pycache__" not in path.parts:
                    files[str(path.relative_to(base))] = path.read_bytes()
    return files


def main() -> None:
    """Generate, or compare with --check."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare, do not write")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp)
        generate(fresh)
        if args.check:
            want, have = tree_files(fresh), tree_files(ROOT)
            diff = sorted(
                name
                for name in want.keys() | have.keys()
                if want.get(name) != have.get(name)
            )
            if diff:
                sys.exit(
                    "the generated files differ from upstream/ + overlay/ "
                    "(run scripts/generate.py):\n  " + "\n  ".join(diff)
                )
            print("generated files match upstream/ + overlay/")
            return
        for rel in (OUT_INTEGRATION, OUT_TESTS):
            shutil.rmtree(ROOT / rel, ignore_errors=True)
        (ROOT / OUT_LOGBOOK_HELPER).unlink(missing_ok=True)
        for rel in (OUT_INTEGRATION, OUT_TESTS):
            shutil.copytree(fresh / rel, ROOT / rel)
        shutil.copy2(fresh / OUT_LOGBOOK_HELPER, ROOT / OUT_LOGBOOK_HELPER)
        shutil.copy2(fresh / TEST_REQUIREMENTS, ROOT / TEST_REQUIREMENTS)
    print("generated custom_components/airdress, tests/airdress and the library pin")


if __name__ == "__main__":
    main()
